apiVersion: v1
kind: Secret
metadata:
  name: cropilot-secrets
type: Opaque
stringData:
  PWD_SECRET: change-me
  MONGODB_PASS: change-me
  MONGODB_URI: mongodb://mongodb-default-username:change-me@mongo-db:27017/database_name?authSource=admin
  HATCHET_CLIENT_TOKEN: change-me
  ADMIN_EMAIL: change-me@email.com
  ADMIN_PASSWORD: change-me
  ADMIN_NAME: Admin
